web:
  image: nagasaki45/krihelinator_web
  ports:
    - 80:80
  links:
    - db
    - stash
  env_file: ./secrets
  restart: always

db:
  image: postgres:9.5
  restart: always

stash:
  image: redis
  restart: always
